import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Montserrat.ttf",
  weight: "400 500",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>{children}</body>
    </html>
  );
}
